$.li18n.translations = {
    "kr": {
        "mac" : "맥 주소",
        "dashboard" : "대시보드",
        "sensors" : "센서",
        "clouds" : "클라우드 연동",
        "network" : "네트워크 정보",
        "system" : "시스템 정보",
        "sensornodes" : "센싱 리스트",
        "rule" : "규칙 관리",
        "register":"센서등록",
        "list": "센서리스트",
        "mac" : "맥 주소",
        "search" : "검색",
        "name" : "이름",
        "type" : "센서 종류",
        "value" : "값",
        "state" : "상태",
        "list" : "리스트",
        "graph" : "그래프",
        "view" : "보기",
        "unit" : "단위",
        "interval" : "수집 주기",
        "close" : "닫기",
        "modify" : "수정",
        "epid" : "센서 ID",
        "timeout" : "타임아웃",
        "url" : "주소",
        "location" : "위치",
        "trigger_add" : "트리거 추가",
        "action_add" : "액션 작성",
        "trigger_title" : "트리거 작성",
        "trigger_type" : "트리거 종류",
        "trigger" : "트리거",
        "action" : "액션",
        "rules" : "규칙 리스트",
        "DEACTIVATE" : "정지",
        "ACTIVATE" : "동작",
        "action_type" : "액션 종류",
        "lower" : "하위 조건값",
        "upper" : "상위 조건값",
        "above" : "이상 일 경우",
        "below" : "이하 일 경우",
        "include" : "범위 내 경우",
        "except" : "범위 외 경우",
        "change" : "변경 된 경우",
        "set" : "액츄에이터 제어",
        "sms" : "SMS 메시지 발송",
        "push" : "Push 메시지 발송",
        "mail" : "이메일 발송",
        "information" : "정보",
        "port" : "포트 이름",
        "ip" : "아이피 주소",
        "subnet" : "서브넷 마스크",
        "apn_setting" : "APN 설정",
        "firewall" : "접근제어",
        "firewall_setting" : "접근제어 설정",
        "number" : "번호",
        "dhcp_setting" : "DHCP 서버 설정",
        "dhcp_info" : "DHCP 서버 정보",
        "add" : "추가",
        "remove" : "삭제",
        "rule_id" : "규칙 ID",
        "rule_name" : "규칙 이름",
        "model" : "모델",
        "sn" : "시리얼 번호",
        "hw_ver" : "하드웨어 버전",
        "modem_ver" : "모뎀 버전",
        "device_info" : "장비 정보",
        "log" : "로그",
        "restart" : "재부팅",
        "system_log" : "시스템 로그",
        "system_reboot" : "시스템 재시작",
        "reboot_message" : "시스템을 재시작 할 수 있습니다.",
        "logout" : "로그아웃",
        "change_pw" : "비밀번호 변경",
        "current_pw" : "기존 비밀번호",
        "new_pw" : "새 비밀번호",
        "confirm_new_pw" : "새 비밀번호 확인",
        "text_active_wan" : "기본 외부망",
        "text_active_interface" : "인터페이스",
        "text_active_dhcp" : "자동으로 주소 받기",
        "text_active_ip" : "IP 주소",
        "text_active_subnet" : "서브넷 마스크",
        "text_active_gateway" : "기본 게이트웨이",
        "text_standby_wan" : "보조 외부망",
        "text_lan" : "내부망",
        "text_register_info" : "※ MAC 주소 혹은 아이피를 입력해 주세요.",
        "reboot_btn" : "재시작",
        "enabled" : "사용",
        "static_ip_address" : "고정IP 설정",
        "ip_start" : "할당 시작 주소",
        "ip_end" : "할당 끝 주소",
        "dns" : "도메인네임주소",
        "leases_time" : "IP 임대기간",
        "static_ip" : "고정 IP",
        "dhcp_ip_info" : "DHCP IP 할당 정보",
        "time_remain" : "남은 시간",
        "apikey_setting" : "API-KEY 설정",
        "btn_register" : "설정",
        "cloud_status" : "클라우드 동작 상태",
        "stop" : "멈춤",
        "start" : "시작",
        "time" : "시간",
        "process" : "프로세스",
        "status_info" : "상태 정보",
    },
    "en": {
        "information" : "Information",
        "dashboard" : "Dashboard",
        "sensors" : "Sensors",
        "clouds" : "Clouds",
        "network" : "Network",
        "system" : "System",
        "sensornodes" : "Sensing List",
        "rule" : "Rule",
        "register":"Register",
        "list": "Sensor List",
        "mac" : "Mac Address",
        "search" : "Search",
        "name" : "Name",
        "type" : "Sensor Type",
        "value" : "Value",
        "state" : "State",
        "list" : "List",
        "graph" : "Graph",
        "view" : "View",
        "unit" : "Unit",
        "interval" : "Interval",
        "close" : "Close",
        "modify" : "Modify",
        "epid" : "Sensor ID",
        "timeout" : "Timeout",
        "url" : "URL",
        "location" : "Location",
        "trigger_add" : "Add Trigger",
        "action_add" : "Add Action",
        "trigger_title" : "Add Trigger",
        "trigger_type" : "Type",
        "trigger" : "Trigger",
        "action" : "Action",
        "rules" : "Rules",
        "DEACTIVATE" : "DEACTIVATE",
        "ACTIVATE" : "ACTIVATE",
        "action_type" : "Action",
        "lower" : "Lower",
        "upper" : "Upper",
        "above" : "Above",
        "below" : "Below",
        "include" : "Include",
        "except" : "Except",
        "change" : "Change",
        "set" : "Actuator Control",
        "sms" : "Send SMS Message",
        "push" : "Send Push Message",
        "mail" : "Send Mail",
        "port" : "Port",
        "ip" : "IP Address",
        "subnet" : "Subnet Mask",
        "apn_setting" : "APN Setting",
        "firewall" : "Filrewall",
        "firewall_setting" : "Firewall Setting",
        "number" : "No",
        "dhcp_setting" : "DHCP Server Setting",
        "dhcp_info" : "DHCP Server Information",
        "add" : "Add",
        "remove" : "Remove",
        "rule_id" : "ID",
        "rule_name" : "Name",
        "model" : "model",
        "sn" : "S/N",
        "hw_ver" : "HW Version",
        "modem_ver" : "Modem Version",
        "device_info" : "Device Information",
        "log" : "log",
        "restart" : "restart",
        "system_log" : "System Log",
        "system_reboot" : "System Reboot",
        "reboot_message" : "Please click the button below For a system restart.",
        "logout" : "Logout",
        "change_pw" : "Chnage Password",
        "current_pw" : "Current Password",
        "new_pw" : "New Password",
        "confirm_new_pw" : "Confirm New Password",
        "text_active_wan" : "Active Wan",
        "text_active_interface" : "Interface",
        "text_active_dhcp" : "DHCP",
        "text_active_ip" : "IP Address",
        "text_active_subnet" : "Subnet Mask",
        "text_active_gateway" : "Gateway",
        "text_standby_wan" : "Standby Wan",
        "text_lan" : "Lan",
        "text_register_info" : "※ Please enter the MAC address or IP Address.",
        "reboot_btn" : "Reboot",
        "enabled" : "Enabled",
        "static_ip_address" : "Static IP Address",
        "ip_start" : "Leases Start",
        "ip_end" : "Leases End",
        "dns" : "DNS",
        "leases_time" : "Leases Time",
        "static_ip" : "Static IP",
        "dhcp_ip_info" : "DHCP IP Information",
        "time_remain" : "Time Remain",
        "apikey_setting" : "API-KEY Setting",
        "btn_register" : "Register",
        "cloud_status" : "Cloud Status",
        "stop" : "Stop",
        "start" : "Start",
        "time" : "Time",
        "process" : "Process",
        "status_info" : "Status",
    },
};