$.li18n.translations = {
    "kr": {
        "dashboard" : "대시보드",
        "sensors" : "센서",
        "clouds" : "클라우드 연동",
        "network" : "네트워크 정보",
        "system" : "시스템 정보",
        "sensornodes" : "센싱 리스트",
        "rule" : "규칙 관리",
        "register":"센서등록",
        "list": "센서리스트",
        "mac" : "맥 주소",
        "search" : "검색",
        "name" : "이름",
        "type" : "센서 종류",
        "value" : "값",
        "state" : "상태",
        "list" : "리스트",
        "graph" : "그래프",
        "view" : "보기",
        "unit" : "단위",
        "interval" : "수집 주기",
        "close" : "닫기",
        "modify" : "수정",
        "epid" : "센서 ID",
        "timeout" : "타임아웃",
        "url" : "주소",
        "location" : "위치",
        "trigger_add" : "트리거 추가",
        "action_add" : "액션 작성",
        "trigger_title" : "트리거 작성",
        "trigger_type" : "트리거 종류",
        "trigger" : "트리거",
        "action" : "액션",
        "rules" : "규칙 리스트",
        "DEACTIVATE" : "정지",
        "ACTIVATE" : "동작",
        "action_type" : "액션 종류",
        "lower" : "하위 조건값",
        "upper" : "상위 조건값",
        "above" : "이상 일 경우",
        "below" : "이하 일 경우",
        "include" : "범위 내 경우",
        "except" : "범위 외 경우",
        "change" : "변경 된 경우",
        "set" : "액츄에이터 제어",
        "sms" : "SMS 메시지 발송",
        "push" : "Push 메시지 발송",
        "mail" : "이메일 발송",
        "information" : "정보",
        "port" : "포트 이름",
        "ip" : "아이피 주소",
        "subnet" : "서브넷 마스크",
        "apn_setting" : "APN 설정",
        "firewall" : "접근제어",
        "firewall_setting" : "접근제어 설정",
        "number" : "번호",
        "dhcp_setting" : "DHCP 서버 설정",
        "dhcp_info" : "DHCP 서버 정보",
        "add" : "추가",
        "remove" : "삭제",
        "rule_id" : "규칙 ID",
        "rule_name" : "규칙 이름",
        "model" : "모델",
        "sn" : "시리얼 번호",
        "hw_ver" : "하드웨어 버전",
        "modem_ver" : "모뎀 버전",
        "device_info" : "장비 정보",
        "log" : "로그",
        "restart" : "재부팅",
        "system_log" : "시스템 로그",
        "system_reboot" : "시스템 재시작",
        "reboot_message" : "시스템을 재시작 할 수 있습니다.",
    },
    "en": {
        "dashboard" : "Dashboard",
        "sensors" : "Sensors",
        "clouds" : "Clouds",
        "network" : "Network",
        "system" : "System",
        "sensornodes" : "Sensing List",
        "rule" : "Rule",
        "register":"Register",
        "list": "Sensor List",
        "mac" : "Mac Address",
        "search" : "Search",
        "name" : "Name",
        "type" : "Sensor Type",
        "value" : "Value",
        "state" : "State",
        "list" : "List",
        "graph" : "Graph",
        "view" : "View",
        "unit" : "Unit",
        "interval" : "Interval",
        "close" : "Close",
        "modify" : "Modify",
        "epid" : "Sensor ID",
        "timeout" : "Timeout",
        "url" : "URL",
        "location" : "Location",
        "trigger_add" : "Add Trigger",
        "action_add" : "Add Action",
        "trigger_title" : "Add Trigger",
        "trigger_type" : "Type",
        "trigger" : "Trigger",
        "action" : "Action",
        "rules" : "Rules",
        "DEACTIVATE" : "DEACTIVATE",
        "ACTIVATE" : "ACTIVATE",
        "action_type" : "Action",
        "lower" : "Lower",
        "upper" : "Upper",
        "above" : "Above",
        "below" : "Below",
        "include" : "Include",
        "except" : "Except",
        "change" : "Change",
        "set" : "Actuator Control",
        "sms" : "Send SMS Message",
        "push" : "Send Push Message",
        "mail" : "Send Mail",
        "port" : "Port",
        "ip" : "IP Address",
        "subnet" : "Subnet Mask",
        "apn_setting" : "APN Setting",
        "firewall" : "Filrewall",
        "firewall_setting" : "Firewall Setting",
        "number" : "No",
        "dhcp_setting" : "DHCP Server Setting",
        "dhcp_info" : "DHCP Server Information",
        "add" : "Add",
        "remove" : "Remove",
        "rule_id" : "ID",
        "rule_name" : "Name",
        "model" : "model",
        "sn" : "S/N",
        "hw_ver" : "HW Version",
        "modem_ver" : "Modem Version",
        "device_info" : "Device Information",
        "log" : "log",
        "restart" : "restart",
        "system_log" : "System Log",
        "system_reboot" : "System Reboot",
        "reboot_message" : "Please click the button below For a system restart.",
    },
};